"""added recipes associated with meal to list

Revision ID: dd465b5ab397
Revises: 82abb7e7f001
Create Date: 2020-10-11 22:16:25.781594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd465b5ab397'
down_revision = '82abb7e7f001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-list',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.create_table('recipe-list',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['user-list.list_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe-list')
    op.drop_table('user-list')
    # ### end Alembic commands ###
