"""name for lists

Revision ID: fc9bf2ade94d
Revises: dd465b5ab397
Create Date: 2020-10-12 10:50:39.718273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9bf2ade94d'
down_revision = 'dd465b5ab397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user-list', sa.Column('list_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user-list_list_name'), 'user-list', ['list_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user-list_list_name'), table_name='user-list')
    op.drop_column('user-list', 'list_name')
    # ### end Alembic commands ###
